version: '3.9'

services:

  smtp:
    container_name: smtp
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025

  sftp:
    container_name: sftp
    image: atmoz/sftp:latest
    command: foo:pass:1001
    ports:
      - 22:22
    volumes:
      - sftp_data:/home/foo/sftp
      - ./sftp/init_sftp.sh:/etc/sftp.d/init.sh:ro
  
  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - sonarqube_data:/opt/sonarqube/data

volumes:
  sftp_data:
    driver: local
  sonarqube_data:
    driver: local